namespace Mvp.Progression
{
    public static partial class TraitCatalog
    {
        /// <summary>奥莉薇 · 焦土流专属卡 20 张,全部携带独占标签 scorch。</summary>
        static TraitCardDefinition[] OliviaExclusive()
        {
            return new[]
            {
                Make("trait_olivia_scorched_hell", "焦土地狱",
                    "攻击命中时,对敌方生命最低单位每秒造成 5% 灼烧伤害,持续 5 秒。",
                    TraitRarity.Epic, 10, 5,
                    EffectFull(TraitEffectKind.ApplyBurn, TraitTriggerKind.OnHit,
                        0.05f, 0f, TraitTargetScope.EnemyLowestHealth, 5f, 1),
                    new[] { "scorch", "burn", "attack" }),
                Make("trait_olivia_beyond_range", "超视距打击",
                    "始终提高全队攻击范围 30%。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.ModifyAttackRange, TraitTriggerKind.Always, 0.30f, 0f),
                    new[] { "scorch", "range", "attack" }),
                Make("trait_olivia_fire_suppress", "火力压制",
                    "攻击命中时,对敌方生命最低单位移动速度降低 10%。", TraitRarity.Epic, 10, 5,
                    EffectScoped(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnHit,
                        0.10f, 0f, TraitTargetScope.EnemyLowestHealth),
                    new[] { "scorch", "slow", "attack" }),
                Make("trait_olivia_doom_judgment", "末日审判",
                    "开战时,所有敌人每秒受到 8% 灼烧伤害,持续 3 秒。",
                    TraitRarity.Epic, 10, 5,
                    EffectFull(TraitEffectKind.ApplyBurn, TraitTriggerKind.OnBattleStart,
                        0.08f, 0f, TraitTargetScope.EnemyAll, 3f, 1),
                    new[] { "scorch", "burn", "control" }),
                Make("trait_olivia_flame_storm", "烈焰风暴",
                    "攻击命中时,对敌方生命最低单位每秒造成 4% 灼烧伤害,持续 4 秒。",
                    TraitRarity.Rare, 7, 3,
                    EffectFull(TraitEffectKind.ApplyBurn, TraitTriggerKind.OnHit,
                        0.04f, 0f, TraitTargetScope.EnemyLowestHealth, 4f, 1),
                    new[] { "scorch", "burn", "attack" }),
                Make("trait_olivia_far_eye", "千里之眼",
                    "始终提高全队攻击范围 15%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyAttackRange, TraitTriggerKind.Always, 0.15f, 0f),
                    new[] { "scorch", "range", "cooldown" }),
                Make("trait_olivia_sustain_burn", "持续灼烧",
                    "敌方处于灼烧状态时,全队攻击力提高 12%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.WhileEnemyBurning,
                        0.12f, 0f),
                    new[] { "scorch", "burn", "attack" }),
                Make("trait_olivia_burn_out", "燃尽",
                    "敌方处于灼烧状态时,对灼烧中的敌人斩杀增伤 15%。", TraitRarity.Rare, 7, 3,
                    EffectScoped(TraitEffectKind.ExecuteBonus, TraitTriggerKind.WhileEnemyBurning,
                        0.15f, 0f, TraitTargetScope.EnemyBurning),
                    new[] { "scorch", "burn", "execute" }),
                AndEffect(
                    Make("trait_olivia_sniper_standby", "狙击待机",
                        "始终提高全队攻击范围 10%,攻击冷却降低 6%。", TraitRarity.Rare, 7, 3,
                        Effect(TraitEffectKind.ModifyAttackRange, TraitTriggerKind.Always, 0.10f, 0f),
                        new[] { "scorch", "range", "cooldown" }),
                    Effect(TraitEffectKind.ModifyAttackCooldown, TraitTriggerKind.Always, 0.06f, 0f)),
                Make("trait_olivia_fire_arrow", "火焰箭",
                    "攻击命中时,对敌方生命最低单位每秒造成 3% 灼烧伤害,持续 3 秒。",
                    TraitRarity.Rare, 7, 3,
                    EffectFull(TraitEffectKind.ApplyBurn, TraitTriggerKind.OnHit,
                        0.03f, 0f, TraitTargetScope.EnemyLowestHealth, 3f, 1),
                    new[] { "scorch", "burn", "attack" }),
                Make("trait_olivia_barrage_suppress", "弹幕压制",
                    "开战时,所有敌人移动速度降低 15%,持续 3 秒。", TraitRarity.Rare, 7, 3,
                    EffectFull(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnBattleStart,
                        0.15f, 0f, TraitTargetScope.EnemyAll, 3f, 1),
                    new[] { "scorch", "slow", "control" }),
                AndEffect(
                    Make("trait_olivia_arsonist", "纵火者",
                        "攻击命中时,对敌方生命最低单位每秒造成 2% 灼烧伤害,持续 2 秒,且攻击冷却降低 6%。",
                        TraitRarity.Rare, 7, 3,
                        EffectFull(TraitEffectKind.ApplyBurn, TraitTriggerKind.OnHit,
                            0.02f, 0f, TraitTargetScope.EnemyLowestHealth, 2f, 1),
                        new[] { "scorch", "burn", "cooldown" }),
                    Effect(TraitEffectKind.ModifyAttackCooldown, TraitTriggerKind.Always, 0.06f, 0f)),
                Make("trait_olivia_burn_shell", "燃烧弹",
                    "攻击命中时,对敌方生命最低单位每秒造成 3% 灼烧伤害,持续 2 秒。",
                    TraitRarity.Common, 5, 2,
                    EffectFull(TraitEffectKind.ApplyBurn, TraitTriggerKind.OnHit,
                        0.03f, 0f, TraitTargetScope.EnemyLowestHealth, 2f, 1),
                    new[] { "scorch", "burn", "attack" }),
                Make("trait_olivia_eye_aim", "鹰眼瞄准",
                    "始终提高全队攻击范围 6%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyAttackRange, TraitTriggerKind.Always, 0.06f, 0f),
                    new[] { "scorch", "range", "attack" }),
                Make("trait_olivia_fire_seed", "火种",
                    "敌方处于灼烧状态时,全队暴击率提高 6%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyCriticalChance, TraitTriggerKind.WhileEnemyBurning,
                        0.06f, 0f),
                    new[] { "scorch", "burn", "critical" }),
                Make("trait_olivia_scorch_spread", "焦土蔓延",
                    "击杀敌人时,附近敌人每秒受到 3% 灼烧伤害,持续 2 秒。",
                    TraitRarity.Common, 5, 2,
                    EffectFull(TraitEffectKind.ApplyBurn, TraitTriggerKind.OnEnemyDeath,
                        0.03f, 0f, TraitTargetScope.NearbyEnemies, 2f, 1),
                    new[] { "scorch", "burn", "attack" }),
                Make("trait_olivia_long_shot", "远距射击",
                    "始终提高全队攻击范围 4%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyAttackRange, TraitTriggerKind.Always, 0.04f, 0f),
                    new[] { "scorch", "range", "cooldown" }),
                Make("trait_olivia_rocket_volley", "火箭齐射",
                    "开战时,全队攻击力提高 8%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.OnBattleStart, 0.08f, 0f),
                    new[] { "scorch", "attack", "first_strike" }),
                Make("trait_olivia_ignite", "引燃",
                    "攻击命中时,对敌方生命最低单位每秒造成 2% 灼烧伤害,持续 3 秒。",
                    TraitRarity.Common, 5, 2,
                    EffectFull(TraitEffectKind.ApplyBurn, TraitTriggerKind.OnHit,
                        0.02f, 0f, TraitTargetScope.EnemyLowestHealth, 3f, 1),
                    new[] { "scorch", "burn", "attack" }),
                Make("trait_olivia_fireline_suppress", "火线压制",
                    "攻击命中时,对敌方生命最低单位移动速度降低 5%。", TraitRarity.Common, 5, 2,
                    EffectScoped(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnHit,
                        0.05f, 0f, TraitTargetScope.EnemyLowestHealth),
                    new[] { "scorch", "slow", "attack" })
            };
        }
    }
}
