namespace Mvp.Progression
{
    public static partial class TraitCatalog
    {
        /// <summary>伊莲娜 · 狂暴流专属卡 20 张,全部携带独占标签 frenzy。</summary>
        static TraitCardDefinition[] ElenaExclusive()
        {
            return new[]
            {
                Make("trait_elena_bloodthirst", "嗜血狂暴",
                    "编队生命低于 50% 时,攻击力提高 25%。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.ModifyAttackPower,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.25f, 0.50f),
                    new[] { "frenzy", "attack", "low_health" }),
                Make("trait_elena_never_fall", "死战不退",
                    "编队生命低于 35% 时,吸血 15%。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.ModifyLifeSteal,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.15f, 0.35f),
                    new[] { "frenzy", "lifesteal", "low_health" }),
                Make("trait_elena_blood_price", "血之代价",
                    "每损失 1% 生命,攻击力提高 0.5%。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.BasedOnHealthLost,
                        0.005f, 1f),
                    new[] { "frenzy", "attack", "max_health" }),
                Make("trait_elena_berserk_moment", "狂暴时刻",
                    "编队生命低于 30% 时,攻击冷却降低 20%。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.ModifyAttackCooldown,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.20f, 0.30f),
                    new[] { "frenzy", "cooldown", "low_health" }),
                Make("trait_elena_battle_blood", "浴血奋战",
                    "编队生命低于 35% 时,所受伤害降低 12%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ReduceIncomingDamage,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.12f, 0.35f),
                    new[] { "frenzy", "defense", "low_health" }),
                Make("trait_elena_hunt_instinct", "猎杀本能",
                    "编队生命低于 50% 时,暴击率提高 10%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyCriticalChance,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.10f, 0.50f),
                    new[] { "frenzy", "critical", "low_health" }),
                Make("trait_elena_bloodstream", "血流如注",
                    "攻击命中时,吸血 5%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyLifeSteal, TraitTriggerKind.OnHit, 0.05f, 0f),
                    new[] { "frenzy", "lifesteal", "attack" }),
                Make("trait_elena_war_frenzy", "战意沸腾",
                    "编队生命低于 50% 时,攻击冷却降低 10%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyAttackCooldown,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.10f, 0.50f),
                    new[] { "frenzy", "cooldown", "low_health" }),
                Make("trait_elena_blood_rush", "嗜血狂飙",
                    "编队生命低于 40% 时,移动速度提高 15%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyMoveSpeed,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.15f, 0.40f),
                    new[] { "frenzy", "mobility", "low_health" }),
                Make("trait_elena_blood_suppress", "血线压制",
                    "编队生命低于 30% 时,攻击力提高 15%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyAttackPower,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.15f, 0.30f),
                    new[] { "frenzy", "attack", "low_health" }),
                Make("trait_elena_fight_stronger", "越战越勇",
                    "击杀敌人时,攻击力提高 5%,本场可叠加。", TraitRarity.Rare, 7, 3,
                    EffectStacks(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.OnEnemyDeath,
                        0.05f, 0f, 0),
                    new[] { "frenzy", "attack", "commander" }),
                Make("trait_elena_deep_grudge", "血海深仇",
                    "我方每损失 1 个单位,攻击力提高 3%。", TraitRarity.Rare, 7, 3,
                    EffectStacks(TraitEffectKind.ModifyAttackPower,
                        TraitTriggerKind.OnFriendlyUnitLost, 0.03f, 0f, 0),
                    new[] { "frenzy", "attack", "commander" }),
                Make("trait_elena_break_pot", "破釜沉舟",
                    "编队生命低于 50% 时,攻击力提高 10%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyAttackPower,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.10f, 0.50f),
                    new[] { "frenzy", "attack", "low_health" }),
                Make("trait_elena_blood_heat", "血性沸腾",
                    "编队生命低于 40% 时,移动速度提高 10%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyMoveSpeed,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.10f, 0.40f),
                    new[] { "frenzy", "mobility", "low_health" }),
                Make("trait_elena_stop_loss", "及时止损",
                    "编队生命低于 35% 时,所受伤害降低 8%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ReduceIncomingDamage,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.08f, 0.35f),
                    new[] { "frenzy", "defense", "low_health" }),
                Make("trait_elena_blood_instinct", "噬血本能",
                    "攻击命中时,吸血 4%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyLifeSteal, TraitTriggerKind.OnHit, 0.04f, 0f),
                    new[] { "frenzy", "lifesteal", "attack" }),
                Make("trait_elena_death_throes", "临死反扑",
                    "编队生命低于 20% 时,暴击率提高 8%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyCriticalChance,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.08f, 0.20f),
                    new[] { "frenzy", "critical", "low_health" }),
                Make("trait_elena_berserk_speed", "狂暴加速",
                    "编队生命低于 40% 时,攻击冷却降低 6%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyAttackCooldown,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.06f, 0.40f),
                    new[] { "frenzy", "cooldown", "low_health" }),
                Make("trait_elena_blood_pact", "血色契约",
                    "始终提高生命上限 6%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyMaxHealth, TraitTriggerKind.Always, 0.06f, 0f),
                    new[] { "frenzy", "max_health", "defense" }),
                AndEffect(
                    Make("trait_elena_cornered", "困兽之斗",
                        "编队生命低于 25% 时,攻击力提高 8%,所受伤害降低 5%。",
                        TraitRarity.Common, 5, 2,
                        Effect(TraitEffectKind.ModifyAttackPower,
                            TraitTriggerKind.WhileGroupHealthBelowPercent, 0.08f, 0.25f),
                        new[] { "frenzy", "attack", "defense" }),
                    Effect(TraitEffectKind.ReduceIncomingDamage,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.05f, 0.25f))
            };
        }
    }
}
