namespace Mvp.Progression
{
    public static partial class TraitCatalog
    {
        /// <summary>达里奥 · 雇佣流专属卡 20 张,全部携带独占标签 mercenary。</summary>
        static TraitCardDefinition[] DarioExclusive()
        {
            return new[]
            {
                Make("trait_dario_mercenary_band", "雇佣兵团",
                    "胜利时,额外获得 10 金币。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.GoldOnWin, TraitTriggerKind.Always, 10f, 0f),
                    new[] { "mercenary", "economy", "commander" }),
                Make("trait_dario_war_loot", "战利品掠夺",
                    "每击杀一个敌人,额外获得 10 金币。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.GoldOnKill, TraitTriggerKind.OnEnemyDeath, 10f, 0f),
                    new[] { "mercenary", "economy", "attack" }),
                Make("trait_dario_commission", "佣金合同",
                    "每拥有 10 金币,全队攻击力提高 1%。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.BasedOnGold,
                        0.01f, 10f),
                    new[] { "mercenary", "economy", "commander" }),
                Make("trait_dario_arms_trade", "军火贸易",
                    "每拥有 10 金币,全队所受伤害降低 0.5%。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.ReduceIncomingDamage, TraitTriggerKind.BasedOnGold,
                        0.005f, 10f),
                    new[] { "mercenary", "economy", "defense" }),
                AndEffect(
                    Make("trait_dario_bounty", "悬赏通缉",
                        "每击杀一个敌人,额外获得 5 金币,且对敌方生命低于 30% 的单位斩杀增伤 15%。",
                        TraitRarity.Rare, 7, 3,
                        Effect(TraitEffectKind.GoldOnKill, TraitTriggerKind.OnEnemyDeath, 5f, 0f),
                        new[] { "mercenary", "economy", "execute" }),
                    EffectScoped(TraitEffectKind.ExecuteBonus, TraitTriggerKind.WhileEnemyLowHealth,
                        0.15f, 0.30f, TraitTargetScope.EnemyLowestHealth)),
                Make("trait_dario_usury", "高利贷",
                    "开战时,金币获取提高 20%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.EconomyModifier, TraitTriggerKind.OnBattleStart, 0.20f, 0f),
                    new[] { "mercenary", "economy", "commander" }),
                Make("trait_dario_elite_mercenary", "佣兵精英",
                    "每拥有 10 金币,全队攻击力提高 0.5%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.BasedOnGold,
                        0.005f, 10f),
                    new[] { "mercenary", "economy", "attack" }),
                Make("trait_dario_field_broker", "战地掮客",
                    "击杀敌人时,全队攻击力提高 5%,本场可叠加。", TraitRarity.Rare, 7, 3,
                    EffectStacks(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.OnEnemyDeath,
                        0.05f, 0f, 0),
                    new[] { "mercenary", "economy", "attack" }),
                AndEffect(
                    Make("trait_dario_insurance", "保险佣金",
                        "开战时,金币获取提高 10%,全队所受伤害降低 5%。", TraitRarity.Rare, 7, 3,
                        Effect(TraitEffectKind.EconomyModifier, TraitTriggerKind.OnBattleStart, 0.10f, 0f),
                        new[] { "mercenary", "economy", "defense" }),
                    Effect(TraitEffectKind.ReduceIncomingDamage, TraitTriggerKind.OnBattleStart, 0.05f, 0f)),
                Make("trait_dario_armament", "军备采购",
                    "每拥有 10 金币,全队生命上限提高 0.3%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyMaxHealth, TraitTriggerKind.BasedOnGold,
                        0.003f, 10f),
                    new[] { "mercenary", "economy", "max_health" }),
                AndEffect(
                    Make("trait_dario_bounty_hunter", "悬红猎手",
                        "每击杀一个敌人,额外获得 5 金币,暴击率提高 6%,本场可叠加。",
                        TraitRarity.Rare, 7, 3,
                        Effect(TraitEffectKind.GoldOnKill, TraitTriggerKind.OnEnemyDeath, 5f, 0f),
                        new[] { "mercenary", "economy", "critical" }),
                    EffectStacks(TraitEffectKind.ModifyCriticalChance, TraitTriggerKind.OnEnemyDeath,
                        0.06f, 0f, 0)),
                AndEffect(
                    Make("trait_dario_market_sense", "市场嗅觉",
                        "开战时,金币获取提高 10%,全队攻击冷却降低 6%。", TraitRarity.Rare, 7, 3,
                        Effect(TraitEffectKind.EconomyModifier, TraitTriggerKind.OnBattleStart, 0.10f, 0f),
                        new[] { "mercenary", "economy", "cooldown" }),
                    Effect(TraitEffectKind.ModifyAttackCooldown, TraitTriggerKind.OnBattleStart, 0.06f, 0f)),
                Make("trait_dario_small_business", "小本生意",
                    "胜利时,额外获得 5 金币。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.GoldOnWin, TraitTriggerKind.Always, 5f, 0f),
                    new[] { "mercenary", "economy", "commander" }),
                Make("trait_dario_body_fee", "收尸费",
                    "每击杀一个敌人,额外获得 5 金币。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.GoldOnKill, TraitTriggerKind.OnEnemyDeath, 5f, 0f),
                    new[] { "mercenary", "economy", "attack" }),
                Make("trait_dario_thrifty", "省钱有道",
                    "始终提高金币获取 8%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.EconomyModifier, TraitTriggerKind.Always, 0.08f, 0f),
                    new[] { "mercenary", "economy", "commander" }),
                Make("trait_dario_money_makes", "钱生钱",
                    "每拥有 10 金币,全队攻击力提高 0.2%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.BasedOnGold,
                        0.002f, 10f),
                    new[] { "mercenary", "economy", "attack" }),
                Make("trait_dario_pay", "军饷",
                    "开战时,全队攻击力提高 6%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.OnBattleStart, 0.06f, 0f),
                    new[] { "mercenary", "attack", "commander" }),
                AndEffect(
                    Make("trait_dario_stockpile", "囤货",
                        "始终提高金币获取 5%,生命上限提高 3%。", TraitRarity.Common, 5, 2,
                        Effect(TraitEffectKind.EconomyModifier, TraitTriggerKind.Always, 0.05f, 0f),
                        new[] { "mercenary", "economy", "max_health" }),
                    Effect(TraitEffectKind.ModifyMaxHealth, TraitTriggerKind.Always, 0.03f, 0f)),
                AndEffect(
                    Make("trait_dario_reward_hunter", "赏金猎人",
                        "每击杀一个敌人,额外获得 5 金币,移动速度提高 4%,本场可叠加。",
                        TraitRarity.Common, 5, 2,
                        Effect(TraitEffectKind.GoldOnKill, TraitTriggerKind.OnEnemyDeath, 5f, 0f),
                        new[] { "mercenary", "economy", "mobility" }),
                    EffectStacks(TraitEffectKind.ModifyMoveSpeed, TraitTriggerKind.OnEnemyDeath,
                        0.04f, 0f, 0)),
                AndEffect(
                    Make("trait_dario_hire_kill", "雇凶",
                        "开战时,金币获取提高 8%,全队攻击冷却降低 4%。", TraitRarity.Common, 5, 2,
                        Effect(TraitEffectKind.EconomyModifier, TraitTriggerKind.OnBattleStart, 0.08f, 0f),
                        new[] { "mercenary", "economy", "cooldown" }),
                    Effect(TraitEffectKind.ModifyAttackCooldown, TraitTriggerKind.OnBattleStart, 0.04f, 0f))
            };
        }
    }
}
