namespace Mvp.Progression
{
    public static partial class TraitCatalog
    {
        /// <summary>卡西安 · 铁壁流专属卡 20 张,全部携带独占标签 bulwark。</summary>
        static TraitCardDefinition[] CassianExclusive()
        {
            return new[]
            {
                Make("trait_cassian_iron_wall", "钢铁壁垒",
                    "开战时,全队获得 20% 生命上限的护盾。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.GrantShield, TraitTriggerKind.OnBattleStart, 0.20f, 0f),
                    new[] { "bulwark", "shield", "formation" }),
                Make("trait_cassian_thorn_reflect", "荆棘反震",
                    "受击时,反弹 10% 所受伤害给攻击者。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.ReflectDamage, TraitTriggerKind.OnReceiveHit, 0.10f, 0f),
                    new[] { "bulwark", "reflect", "defense" }),
                Make("trait_cassian_hold_line", "坚守阵线",
                    "阵型完整时,全队所受伤害降低 10%。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.ReduceIncomingDamage, TraitTriggerKind.WhileFormationIntact,
                        0.10f, 0f),
                    new[] { "bulwark", "defense", "formation" }),
                AndEffect(
                    Make("trait_cassian_immovable", "不动如山",
                        "开战时,全队获得 15% 生命上限的护盾,且生命上限提高 5%。",
                        TraitRarity.Epic, 10, 5,
                        Effect(TraitEffectKind.GrantShield, TraitTriggerKind.OnBattleStart, 0.15f, 0f),
                        new[] { "bulwark", "shield", "max_health" }),
                    Effect(TraitEffectKind.ModifyMaxHealth, TraitTriggerKind.Always, 0.05f, 0f)),
                Make("trait_cassian_iron_formation", "铁壁阵型",
                    "阵型完整时,全队所受伤害降低 8%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ReduceIncomingDamage, TraitTriggerKind.WhileFormationIntact,
                        0.08f, 0f),
                    new[] { "bulwark", "defense", "formation" }),
                Make("trait_cassian_shield_wall", "盾墙推进",
                    "始终降低全队所受伤害 6%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ReduceIncomingDamage, TraitTriggerKind.Always, 0.06f, 0f),
                    new[] { "bulwark", "defense", "shield" }),
                Make("trait_cassian_counter_hammer", "反击重锤",
                    "受击时,反弹 6% 所受伤害给攻击者。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ReflectDamage, TraitTriggerKind.OnReceiveHit, 0.06f, 0f),
                    new[] { "bulwark", "reflect", "defense" }),
                Make("trait_cassian_body_guard", "护体真气",
                    "开战时,全队获得 10% 生命上限的护盾。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.GrantShield, TraitTriggerKind.OnBattleStart, 0.10f, 0f),
                    new[] { "bulwark", "shield", "defense" }),
                Make("trait_cassian_trade_defense", "以伤换守",
                    "编队生命高于 70% 时,全队所受伤害降低 10%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ReduceIncomingDamage,
                        TraitTriggerKind.WhileGroupHealthAbovePercent, 0.10f, 0.70f),
                    new[] { "bulwark", "defense", "sustain" }),
                Make("trait_cassian_heavy_crush", "重甲碾压",
                    "阵型完整时,全队攻击力提高 10%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.WhileFormationIntact,
                        0.10f, 0f),
                    new[] { "bulwark", "attack", "formation" }),
                Make("trait_cassian_copper_wall", "铜墙铁壁",
                    "编队生命高于 70% 时,全队获得 8% 生命上限的护盾。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.GrantShield,
                        TraitTriggerKind.WhileGroupHealthAbovePercent, 0.08f, 0.70f),
                    new[] { "bulwark", "shield", "high_health" }),
                Make("trait_cassian_unyielding", "不屈意志",
                    "编队生命低于 40% 时,全队所受伤害降低 12%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ReduceIncomingDamage,
                        TraitTriggerKind.WhileGroupHealthBelowPercent, 0.12f, 0.40f),
                    new[] { "bulwark", "defense", "low_health" }),
                Make("trait_cassian_iron_shell", "铁壳",
                    "始终降低全队所受伤害 4%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ReduceIncomingDamage, TraitTriggerKind.Always, 0.04f, 0f),
                    new[] { "bulwark", "defense" }),
                Make("trait_cassian_shield_bash", "盾击",
                    "攻击命中时,对敌方生命最低单位移动速度降低 5%。", TraitRarity.Common, 5, 2,
                    EffectScoped(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnHit,
                        0.05f, 0f, TraitTargetScope.EnemyLowestHealth),
                    new[] { "bulwark", "slow", "defense" }),
                Make("trait_cassian_shield_bracket", "护盾支架",
                    "始终提高全队生命上限 5%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyMaxHealth, TraitTriggerKind.Always, 0.05f, 0f),
                    new[] { "bulwark", "max_health", "defense" }),
                Make("trait_cassian_line_fortify", "防线加固",
                    "开战时,全队获得 5% 生命上限的护盾。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.GrantShield, TraitTriggerKind.OnBattleStart, 0.05f, 0f),
                    new[] { "bulwark", "shield", "formation" }),
                Make("trait_cassian_tight_formation", "阵型紧凑",
                    "阵型完整时,全队所受伤害降低 5%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ReduceIncomingDamage, TraitTriggerKind.WhileFormationIntact,
                        0.05f, 0f),
                    new[] { "bulwark", "defense", "formation" }),
                Make("trait_cassian_shoulder_reflect", "肩甲反弹",
                    "受击时,反弹 4% 所受伤害给攻击者。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ReflectDamage, TraitTriggerKind.OnReceiveHit, 0.04f, 0f),
                    new[] { "bulwark", "reflect", "defense" }),
                AndEffect(
                    Make("trait_cassian_rock_firm", "坚如磐石",
                        "始终降低全队所受伤害 3%,生命上限提高 3%。", TraitRarity.Common, 5, 2,
                        Effect(TraitEffectKind.ReduceIncomingDamage, TraitTriggerKind.Always, 0.03f, 0f),
                        new[] { "bulwark", "defense", "max_health" }),
                    Effect(TraitEffectKind.ModifyMaxHealth, TraitTriggerKind.Always, 0.03f, 0f)),
                Make("trait_cassian_rest_work", "以逸待劳",
                    "编队生命高于 70% 时,全队攻击冷却降低 6%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyAttackCooldown,
                        TraitTriggerKind.WhileGroupHealthAbovePercent, 0.06f, 0.70f),
                    new[] { "bulwark", "cooldown", "defense" })
            };
        }
    }
}
