namespace Mvp.Progression
{
    public static partial class TraitCatalog
    {
        /// <summary>伊凡 · 冰霜流专属卡 20 张,全部携带独占标签 frost。</summary>
        static TraitCardDefinition[] IvanExclusive()
        {
            return new[]
            {
                Make("trait_ivan_frost_nova", "冰霜新星",
                    "开战时,所有敌人移动速度降低 30%,持续 3 秒。", TraitRarity.Epic, 10, 5,
                    EffectFull(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnBattleStart,
                        0.30f, 0f, TraitTargetScope.EnemyAll, 3f, 1),
                    new[] { "frost", "slow", "control" }),
                Make("trait_ivan_frozen_zone", "极寒之域",
                    "始终使附近敌人移动速度降低 20%。", TraitRarity.Epic, 10, 5,
                    EffectScoped(TraitEffectKind.SlowEnemy, TraitTriggerKind.Always,
                        0.20f, 0f, TraitTargetScope.NearbyEnemies),
                    new[] { "frost", "slow", "idle" }),
                Make("trait_ivan_frost_pact", "霜之契约",
                    "敌方处于减速状态时,对其伤害提高 15%。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.ModifyDamageVsSlowed, TraitTriggerKind.WhileEnemySlowed,
                        0.15f, 0f),
                    new[] { "frost", "control", "attack" }),
                Make("trait_ivan_absolute_zero", "绝对零度",
                    "开战时,所有敌人眩晕 1.5 秒。", TraitRarity.Epic, 10, 5,
                    EffectFull(TraitEffectKind.StunEnemy, TraitTriggerKind.OnBattleStart,
                        1.5f, 0f, TraitTargetScope.EnemyAll, 0f, 1),
                    new[] { "frost", "control", "slow" }),
                Make("trait_ivan_frost_imprison", "寒霜禁锢",
                    "开战时,所有敌人移动速度降低 25%,持续 3 秒。", TraitRarity.Rare, 7, 3,
                    EffectFull(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnBattleStart,
                        0.25f, 0f, TraitTargetScope.EnemyAll, 3f, 1),
                    new[] { "frost", "slow", "control" }),
                Make("trait_ivan_frozen_earth", "冰封大地",
                    "始终使附近敌人移动速度降低 15%。", TraitRarity.Rare, 7, 3,
                    EffectScoped(TraitEffectKind.SlowEnemy, TraitTriggerKind.Always,
                        0.15f, 0f, TraitTargetScope.NearbyEnemies),
                    new[] { "frost", "slow", "idle" }),
                Make("trait_ivan_frost_blade", "霜之利刃",
                    "敌方处于减速状态时,全队暴击率提高 10%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyCriticalChance, TraitTriggerKind.WhileEnemySlowed,
                        0.10f, 0f),
                    new[] { "frost", "control", "critical" }),
                Make("trait_ivan_ice_body", "寒冰护体",
                    "受击时,所有敌人移动速度降低 10%。", TraitRarity.Rare, 7, 3,
                    EffectScoped(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnReceiveHit,
                        0.10f, 0f, TraitTargetScope.EnemyAll),
                    new[] { "frost", "slow", "defense" }),
                Make("trait_ivan_frost_spread", "冰霜蔓延",
                    "击杀敌人时,附近敌人移动速度降低 10%,持续 2 秒。", TraitRarity.Rare, 7, 3,
                    EffectFull(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnEnemyDeath,
                        0.10f, 0f, TraitTargetScope.NearbyEnemies, 2f, 1),
                    new[] { "frost", "slow", "control" }),
                Make("trait_ivan_frozen_prey", "冻结的猎物",
                    "敌方处于减速状态时,对减速中的敌人斩杀增伤 15%。", TraitRarity.Rare, 7, 3,
                    EffectScoped(TraitEffectKind.ExecuteBonus, TraitTriggerKind.WhileEnemySlowed,
                        0.15f, 0f, TraitTargetScope.EnemySlowed),
                    new[] { "frost", "control", "execute" }),
                Make("trait_ivan_north_wind", "北风呼号",
                    "敌方处于减速状态时,全队攻击冷却降低 10%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyAttackCooldown, TraitTriggerKind.WhileEnemySlowed,
                        0.10f, 0f),
                    new[] { "frost", "control", "cooldown" }),
                AndEffect(
                    Make("trait_ivan_ice_shard", "冰晶散射",
                        "开战时,所有敌人移动速度降低 20%,持续 2 秒,且全队攻击力提高 8%。",
                        TraitRarity.Rare, 7, 3,
                        EffectFull(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnBattleStart,
                            0.20f, 0f, TraitTargetScope.EnemyAll, 2f, 1),
                        new[] { "frost", "slow", "attack" }),
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.OnBattleStart, 0.08f, 0f)),
                Make("trait_ivan_chill", "寒气袭人",
                    "攻击命中时,对敌方生命最低单位移动速度降低 5%。", TraitRarity.Common, 5, 2,
                    EffectScoped(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnHit,
                        0.05f, 0f, TraitTargetScope.EnemyLowestHealth),
                    new[] { "frost", "slow", "attack" }),
                Make("trait_ivan_frost_road", "冰霜之路",
                    "始终使附近敌人移动速度降低 8%。", TraitRarity.Common, 5, 2,
                    EffectScoped(TraitEffectKind.SlowEnemy, TraitTriggerKind.Always,
                        0.08f, 0f, TraitTargetScope.NearbyEnemies),
                    new[] { "frost", "slow", "defense" }),
                AndEffect(
                    Make("trait_ivan_frostbite", "冻伤",
                        "攻击命中时,对敌方生命最低单位移动速度降低 3%,且对敌方生命低于 30% 的单位斩杀增伤 5%。",
                        TraitRarity.Common, 5, 2,
                        EffectScoped(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnHit,
                            0.03f, 0f, TraitTargetScope.EnemyLowestHealth),
                        new[] { "frost", "slow", "execute" }),
                    EffectScoped(TraitEffectKind.ExecuteBonus, TraitTriggerKind.WhileEnemyLowHealth,
                        0.05f, 0.30f, TraitTargetScope.EnemyLowestHealth)),
                Make("trait_ivan_cold_wind", "冷风拂面",
                    "敌方处于减速状态时,全队移动速度提高 6%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyMoveSpeed, TraitTriggerKind.WhileEnemySlowed,
                        0.06f, 0f),
                    new[] { "frost", "control", "mobility" }),
                Make("trait_ivan_ice_spike", "冰棱",
                    "开战时,所有敌人移动速度降低 10%,持续 2 秒。", TraitRarity.Common, 5, 2,
                    EffectFull(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnBattleStart,
                        0.10f, 0f, TraitTargetScope.EnemyAll, 2f, 1),
                    new[] { "frost", "slow", "control" }),
                AndEffect(
                    Make("trait_ivan_frost_armor", "霜冻护甲",
                        "受击时,所有敌人移动速度降低 5%,且全队所受伤害降低 3%。",
                        TraitRarity.Common, 5, 2,
                        EffectScoped(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnReceiveHit,
                            0.05f, 0f, TraitTargetScope.EnemyAll),
                        new[] { "frost", "slow", "defense" }),
                    Effect(TraitEffectKind.ReduceIncomingDamage, TraitTriggerKind.Always, 0.03f, 0f)),
                AndEffect(
                    Make("trait_ivan_ice_stab", "冰锥刺骨",
                        "攻击命中时,对敌方生命最低单位移动速度降低 5%,且全队暴击率提高 4%。",
                        TraitRarity.Common, 5, 2,
                        EffectScoped(TraitEffectKind.SlowEnemy, TraitTriggerKind.OnHit,
                            0.05f, 0f, TraitTargetScope.EnemyLowestHealth),
                        new[] { "frost", "slow", "critical" }),
                    Effect(TraitEffectKind.ModifyCriticalChance, TraitTriggerKind.Always, 0.04f, 0f)),
                Make("trait_ivan_night_hunt", "寒夜狩猎",
                    "敌方处于减速状态时,全队攻击力提高 6%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.WhileEnemySlowed,
                        0.06f, 0f),
                    new[] { "frost", "control", "attack" })
            };
        }
    }
}
