namespace Mvp.Progression
{
    public static partial class TraitCatalog
    {
        /// <summary>薇拉 · 暗杀流专属卡 20 张,全部携带独占标签 lethality。</summary>
        static TraitCardDefinition[] VeraExclusive()
        {
            return new[]
            {
                Make("trait_vera_lethal_blow", "致命一击",
                    "始终提高全队暴击率 20%。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.ModifyCriticalChance, TraitTriggerKind.Always, 0.20f, 0f),
                    new[] { "lethality", "critical", "attack" }),
                Make("trait_vera_beheading", "斩首行动",
                    "敌方生命低于 30% 时,对敌方生命最低单位斩杀增伤 50%。",
                    TraitRarity.Epic, 10, 5,
                    EffectScoped(TraitEffectKind.ExecuteBonus, TraitTriggerKind.WhileEnemyLowHealth,
                        0.50f, 0.30f, TraitTargetScope.EnemyLowestHealth),
                    new[] { "lethality", "execute", "attack" }),
                Make("trait_vera_shadow_strike", "影袭",
                    "开战时,先手攻击力提高 20%,持续 3 秒。", TraitRarity.Epic, 10, 5,
                    EffectTimed(TraitEffectKind.FirstStrikeBonus, TraitTriggerKind.OnBattleStart,
                        0.20f, 0f, 3f),
                    new[] { "lethality", "first_strike", "mobility" }),
                Make("trait_vera_death_descend", "死神降临",
                    "始终提高全队暴击伤害 50%。", TraitRarity.Epic, 10, 5,
                    Effect(TraitEffectKind.ModifyCriticalDamage, TraitTriggerKind.Always, 0.50f, 0f),
                    new[] { "lethality", "critical", "attack" }),
                Make("trait_vera_fatal_weakness", "致命弱点",
                    "敌方生命低于 40% 时,对敌方生命最低单位斩杀增伤 30%。", TraitRarity.Rare, 7, 3,
                    EffectScoped(TraitEffectKind.ExecuteBonus, TraitTriggerKind.WhileEnemyLowHealth,
                        0.30f, 0.40f, TraitTargetScope.EnemyLowestHealth),
                    new[] { "lethality", "execute", "attack" }),
                Make("trait_vera_falcon_dive", "风隼俯冲",
                    "开战时,全队移动速度提高 15%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyMoveSpeed, TraitTriggerKind.OnBattleStart, 0.15f, 0f),
                    new[] { "lethality", "mobility", "first_strike" }),
                Make("trait_vera_ruthless_chase", "冷酷追击",
                    "击杀敌人时,全队移动速度提高 8%,本场可叠加。", TraitRarity.Rare, 7, 3,
                    EffectStacks(TraitEffectKind.ModifyMoveSpeed, TraitTriggerKind.OnEnemyDeath,
                        0.08f, 0f, 0),
                    new[] { "lethality", "mobility", "attack" }),
                Make("trait_vera_weakness_insight", "弱点洞悉",
                    "敌方生命低于 50% 时,全队暴击率提高 10%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyCriticalChance, TraitTriggerKind.WhileEnemyLowHealth,
                        0.10f, 0.50f),
                    new[] { "lethality", "critical", "execute" }),
                Make("trait_vera_shadow_step", "暗影步",
                    "始终提高全队移动速度 8%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyMoveSpeed, TraitTriggerKind.Always, 0.08f, 0f),
                    new[] { "lethality", "mobility", "defense" }),
                Make("trait_vera_poison_blade", "淬毒利刃",
                    "攻击命中时,对敌方生命最低单位破甲 8%。", TraitRarity.Rare, 7, 3,
                    EffectScoped(TraitEffectKind.ReduceEnemyDefense, TraitTriggerKind.OnHit,
                        0.08f, 0f, TraitTargetScope.EnemyLowestHealth),
                    new[] { "lethality", "armor_pen", "attack" }),
                Make("trait_vera_gale_combo", "疾风连击",
                    "始终降低全队攻击冷却 10%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyAttackCooldown, TraitTriggerKind.Always, 0.10f, 0f),
                    new[] { "lethality", "cooldown", "attack" }),
                Make("trait_vera_hunt_moment", "猎杀时刻",
                    "开战时,全队攻击力提高 12%。", TraitRarity.Rare, 7, 3,
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.OnBattleStart, 0.12f, 0f),
                    new[] { "lethality", "attack", "first_strike" }),
                Make("trait_vera_cold_blood", "冷血",
                    "始终提高全队暴击率 6%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyCriticalChance, TraitTriggerKind.Always, 0.06f, 0f),
                    new[] { "lethality", "critical", "attack" }),
                Make("trait_vera_quick_hand", "快手",
                    "始终降低全队攻击冷却 5%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyAttackCooldown, TraitTriggerKind.Always, 0.05f, 0f),
                    new[] { "lethality", "cooldown", "attack" }),
                Make("trait_vera_light_march", "轻装疾行",
                    "始终提高全队移动速度 6%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyMoveSpeed, TraitTriggerKind.Always, 0.06f, 0f),
                    new[] { "lethality", "mobility", "defense" }),
                Make("trait_vera_throat_cut", "见血封喉",
                    "敌方生命低于 30% 时,对敌方生命最低单位斩杀增伤 15%。", TraitRarity.Common, 5, 2,
                    EffectScoped(TraitEffectKind.ExecuteBonus, TraitTriggerKind.WhileEnemyLowHealth,
                        0.15f, 0.30f, TraitTargetScope.EnemyLowestHealth),
                    new[] { "lethality", "execute", "attack" }),
                Make("trait_vera_first_strike", "先手之利",
                    "开战时,先手攻击力提高 10%,持续 3 秒。", TraitRarity.Common, 5, 2,
                    EffectTimed(TraitEffectKind.FirstStrikeBonus, TraitTriggerKind.OnBattleStart,
                        0.10f, 0f, 3f),
                    new[] { "lethality", "first_strike", "attack" }),
                Make("trait_vera_gap_catch", "破绽捕捉",
                    "敌方生命低于 50% 时,全队攻击力提高 8%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.WhileEnemyLowHealth,
                        0.08f, 0.50f),
                    new[] { "lethality", "attack", "execute" }),
                Make("trait_vera_shadow_weave", "疾影穿梭",
                    "击杀敌人时,全队攻击力提高 4%,本场可叠加。", TraitRarity.Common, 5, 2,
                    EffectStacks(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.OnEnemyDeath,
                        0.04f, 0f, 0),
                    new[] { "lethality", "attack", "commander" }),
                Make("trait_vera_ambush", "暗袭",
                    "首次攻击时,全队攻击力提高 8%。", TraitRarity.Common, 5, 2,
                    Effect(TraitEffectKind.ModifyAttackPower, TraitTriggerKind.OnFirstAttack, 0.08f, 0f),
                    new[] { "lethality", "attack", "first_strike" })
            };
        }
    }
}
